version: "3.8"

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data: