version: 2.1
orbs: 
  slack: circleci/slack@4.7.1


jobs:
  build_and_test:
    docker:
      - image: circleci/classic:edge
    steps:
      - run:
          name: build-docker-compose
          command: docker-compose -f docker-compose.yml up -d --build
      - run:
          name: run-test
          command: docker-compose exec web python3 manage.py test
      - run:
          name: down-docker-compose
          command: docker-compose -f docker-compose.yml down
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1
      # - persist_to_workspace:
      #     root: ~/univ_app
      #     paths:
      #       - .
  conoha_deploy:
    docker:
      - image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${FINGERPRINTS}
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "cd ~; git pull; cd univ_app; docker-compose up -d"

workflows:
  version: 2
  on_commit:
    jobs:
      # - build_and_test
      - conoha_deploy:
          # requires:
          #   - build_and_test
          filters:
            branches:
              only: main


# https://qiita.com/Kesin11/items/47079bc7f659e71b694c


