version: 2.1
orbs: 
  slack: circleci/slack@4.7.1

commands:
  install_docker_compose:
    steps:
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

jobs:
  # build_and_test:
  #   docker:
  #     - image: circleci/classic:edge
  #   steps:
  #     - checkout
  #     - run:
  #         name: build-docker-compose
  #         command: docker-compose -f docker-compose.yml up -d --build
  #     - run:
  #         name: run-test
  #         command: docker-compose exec web python3 manage.py test
  #     - run:
  #         name: down-docker-compose
  #         command: docker-compose -f docker-compose.yml down
  #     # - store_test_results:
  #     #     path: test-results
  #     # - store_artifacts:
  #     #     path: test-results
  #     #     destination: tr1
  #     # - persist_to_workspace:
  #     #     root: ~/univ_app
  #     #     paths:
  #     #       - .

  conoha_deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINTS
      - run:
          name: Decode env file for docker
          command: echo $DOCKER_ENV_FILE | base64 --decode > .env
      - run:
          name: Decode env file fot django setting
          command: echo $DJANGO_SETTING_ENV_FILE | base64 --decode > ./django/.env
      - run:
          name: Deploy Over SSH
          command: |
            pwd
            ls -al
            ssh $SSH_USERNAME@$SSH_HOST "./deploy.sh"

workflows:
  version: 2
  on_commit:
    jobs:
      # - build_and_test
      - conoha_deploy:
          # requires:
          #   - build_and_test
          filters:
            branches:
              only: main

# https://qiita.com/Kesin11/items/47079bc7f659e71b694c
