# Generated by Django 3.1.7 on 2022-01-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220112_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
